# filename: .rubocop.yml

AllCops:
  Exclude:
    - Rakefile
  TargetRubyVersion: 2.3

AbcSize:
  Enabled: false

MethodLength:
  Max: 25

StringLiterals:
  EnforcedStyle: single_quotes

StructInheritance:
  Enabled: false

PredicateName:
  Enabled: false
